apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cfmap
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}
